spring:
  mail:
    host: ${SMTP_HOST:smtp.gmail.com}
    port: ${SMTP_PORT:587}
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: ${SMTP_HOST:smtp.gmail.com}
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:admin}
    url: ${DB_URI:jdbc:postgresql://localhost:5432/ams}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: ams
server:
  port: ${PORT:8888}